site_name: ts-framework
site_url: https://ts-framework.docs.bailey.sh/
site_author: Bailey Herbert
site_description:

repo_name: ts-framework/framework
repo_url: https://github.com/ts-framework/framework
edit_uri: ""

theme:
  name: material
  custom_dir: docs/assets/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/styles.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
      separator: '-'
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.saneheaders
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Getting started:
    - Installation: getting-started/installation.md
    - Creating applications: getting-started/creating-applications.md
    - Creating modules: getting-started/creating-modules.md
    - Creating services: getting-started/creating-services.md
    - Creating controllers: getting-started/creating-controllers.md
    - Creating events: getting-started/creating-events.md
    - Creating attributes: getting-started/creating-attributes.md
  - Working with applications:
    - Configuring applications: applications/configuring-applications.md
    - Managing applications: applications/managing-applications.md
    - Sending events: applications/sending-events.md
    - Sending requests: applications/sending-requests.md
  - Working with modules:
    - Configuring modules: modules/configuring-modules.md
    - Importing modules: modules/importing-modules.md
    - Lifecycle methods: modules/lifecycle-methods.md
  - Working with services:
    - Implementing services: services/implementing-services.md
    - Implementing state: services/implementing-state.md
    - Adding events: services/adding-events.md
    - Adding requests: services/adding-requests.md
    - Adding attributes: services/adding-attributes.md
    - Tracking promises: services/tracking-promises.md
    - Timeouts & intervals: services/timeouts-intervals.md
  - Working with controllers:
    - Implementing controllers: controllers/implementing-controllers.md
    - Using attributes: controllers/using-attributes.md
    - Handling events: controllers/handling-events.md
    - Handling requests: controllers/handling-requests.md
  - Working with extensions:
    - Using extensions: extensions/using-extensions.md
    - Developing extensions: extensions/developing-extensions.md
    - Extension modules: extensions/extension-modules.md
  - Techniques:
    - Error handling: techniques/error-handling.md
    - Configuration: techniques/configuration.md
    - Storage: techniques/storage.md
    - Logging: techniques/logging.md
    - Scheduling: techniques/scheduling.md
    - Queues: techniques/queues.md
  - Integrations:
    - Express: integrations/express.md
    - Discord: integrations/discord.md

plugins:
  - search

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ts-framework
